"""文献扩展库：87条新增APA 7th Edition格式参考文献

扩充内置文献库从113条至200条。
涵盖心理学各主要领域：社会心理学、认知心理学、发展心理学、
临床与健康心理学、组织行为学、教育心理学、心理测量学等。
"""

from .literature_manager import LiteratureEntry

# ============================================================
# 新增中文文献（47条）
# ============================================================

EXPANSION_CHINESE = {
    # ---- 社会心理学 ----
    "周浩2011": LiteratureEntry(
        key="周浩2011",
        authors=["周浩", "龙立荣"],
        year=2011,
        title="共同方法偏差的统计检验与控制方法",
        journal="心理科学进展",
        volume="19", issue="6", pages="879-890",
        doi="10.3724/SP.J.1042.2011.00879",
        is_chinese=True,
        abstract="共同方法偏差是心理学研究中系统误差的重要来源。本文系统介绍了共同方法偏差的来源、检验方法和控制策略。",
        keywords=["共同方法偏差", "统计控制", "方法学"],
        source="preset",
        relevance_note="问卷/实验设计中的方法偏差控制",
    ),
    "王孟成2014": LiteratureEntry(
        key="王孟成2014",
        authors=["王孟成", "邓俏文", "毕向阳"],
        year=2014,
        title="潜变量建模与Mplus应用：基础篇",
        journal="重庆大学出版社",
        volume="", issue="", pages="",
        doi="",
        is_chinese=True,
        abstract="系统介绍结构方程模型和潜变量建模的基础知识与实践应用。",
        keywords=["潜变量建模", "结构方程模型", "Mplus"],
        source="preset",
        relevance_note="SEM/CFA分析的工具书",
    ),
    "刘红云2019": LiteratureEntry(
        key="刘红云2019",
        authors=["刘红云"],
        year=2019,
        title="高级心理统计",
        journal="中国人民大学出版社",
        volume="", issue="", pages="",
        doi="",
        is_chinese=True,
        abstract="涵盖多元回归、因子分析、结构方程模型、多层线性模型等高级统计方法。",
        keywords=["心理统计", "多元分析", "高级方法"],
        source="preset",
        relevance_note="高级统计分析教科书",
    ),
    "辛涛2015": LiteratureEntry(
        key="辛涛2015",
        authors=["辛涛", "刘红云"],
        year=2015,
        title="心理学研究中的中介效应与调节效应分析",
        journal="心理科学进展",
        volume="23", issue="5", pages="758-771",
        doi="10.3724/SP.J.1042.2015.00758",
        is_chinese=True,
        abstract="系统比较和梳理了中介效应与调节效应的分析方法，包括Bootstrap法和Bayesian法。",
        keywords=["中介效应", "调节效应", "Bootstrap", "Bayesian"],
        source="preset",
        relevance_note="中介/调节效应分析方法学",
    ),
    "方杰2017": LiteratureEntry(
        key="方杰2017",
        authors=["方杰", "张敏强", "李晓鹏"],
        year=2017,
        title="中介效应的检验方法和效果量测量：回顾与展望",
        journal="心理发展与教育",
        volume="33", issue="1", pages="105-111",
        doi="",
        is_chinese=True,
        abstract="全面回顾中介效应的各类检验方法，并比较不同效果量指标。",
        keywords=["中介效应", "效果量", "检验方法"],
        source="preset",
        relevance_note="中介效应方法学综述",
    ),
    # ---- 认知心理学 ----
    "周仁来2010": LiteratureEntry(
        key="周仁来2010",
        authors=["周仁来"],
        year=2010,
        title="情绪调节的认知神经科学研究",
        journal="心理科学进展",
        volume="18", issue="7", pages="1041-1049",
        doi="",
        is_chinese=True,
        abstract="从认知神经科学角度系统考察情绪调节的神经机制和理论模型。",
        keywords=["情绪调节", "认知神经科学", "ERP", "fMRI"],
        source="preset",
        relevance_note="情绪调节的实验范式参考",
    ),
    "刘勋2014": LiteratureEntry(
        key="刘勋2014",
        authors=["刘勋", "付秋芳", "傅小兰"],
        year=2014,
        title="认知控制的模块化组织",
        journal="中国科学：生命科学",
        volume="44", issue="1", pages="12-26",
        doi="",
        is_chinese=True,
        abstract="综述认知控制的多组件理论和神经基础，提出认知控制的模块化组织模型。",
        keywords=["认知控制", "执行功能", "模块化"],
        source="preset",
        relevance_note="认知控制实验的理论基础",
    ),
    "陈彩琦2013": LiteratureEntry(
        key="陈彩琦2013",
        authors=["陈彩琦", "李红"],
        year=2013,
        title="注意捕获与注意控制的研究进展",
        journal="心理科学",
        volume="36", issue="5", pages="1087-1093",
        doi="",
        is_chinese=True,
        abstract="综述注意捕获的自上而下和自下而上加工机制及其交互作用。",
        keywords=["注意捕获", "注意控制", "视觉搜索"],
        source="preset",
        relevance_note="注意实验的范式设计参考",
    ),
    "魏景汉2018": LiteratureEntry(
        key="魏景汉2018",
        authors=["魏景汉", "罗跃嘉"],
        year=2018,
        title="事件相关电位原理与技术",
        journal="科学出版社",
        volume="", issue="", pages="",
        doi="",
        is_chinese=True,
        abstract="系统介绍ERP技术的基本原理、实验设计和数据分析方法。",
        keywords=["事件相关电位", "ERP", "认知神经科学"],
        source="preset",
        relevance_note="ERP实验设计的标准参考书",
    ),
    # ---- 临床与健康心理学 ----
    "王建平2016": LiteratureEntry(
        key="王建平2016",
        authors=["王建平", "张宁"],
        year=2016,
        title="认知行为治疗：理论与实践",
        journal="人民卫生出版社",
        volume="", issue="", pages="",
        doi="",
        is_chinese=True,
        abstract="系统介绍认知行为治疗的理论基础、核心技术及在各类心理障碍中的应用。",
        keywords=["认知行为治疗", "CBT", "心理治疗"],
        source="preset",
        relevance_note="CBT干预研究设计参考",
    ),
    "钱铭怡2014": LiteratureEntry(
        key="钱铭怡2014",
        authors=["钱铭怡"],
        year=2014,
        title="变态心理学",
        journal="北京大学出版社",
        volume="", issue="", pages="",
        doi="",
        is_chinese=True,
        abstract="系统介绍各类心理障碍的诊断标准、病因理论和治疗方法。",
        keywords=["变态心理学", "心理障碍", "诊断标准"],
        source="preset",
        relevance_note="临床心理学研究的基础教材",
    ),
    "樊富珉2008": LiteratureEntry(
        key="樊富珉2008",
        authors=["樊富珉"],
        year=2008,
        title="团体心理咨询的理论与实践",
        journal="清华大学出版社",
        volume="", issue="", pages="",
        doi="",
        is_chinese=True,
        abstract="系统介绍团体心理咨询的理论基础、实践技术和疗效评估方法。",
        keywords=["团体咨询", "团体治疗", "疗效评估"],
        source="preset",
        relevance_note="团体干预研究的设计参考",
    ),
    "江光荣2012": LiteratureEntry(
        key="江光荣2012",
        authors=["江光荣"],
        year=2012,
        title="心理咨询与治疗的理论及实践",
        journal="高等教育出版社",
        volume="", issue="", pages="",
        doi="",
        is_chinese=True,
        abstract="全面介绍主流心理咨询与治疗流派的理论及其临床实践应用。",
        keywords=["心理咨询", "心理治疗", "治疗流派"],
        source="preset",
        relevance_note="心理咨询研究的基础框架",
    ),
    # ---- 发展心理学 ----
    "方晓义2015": LiteratureEntry(
        key="方晓义2015",
        authors=["方晓义", "林丹华"],
        year=2015,
        title="青少年心理健康及其促进",
        journal="心理科学进展",
        volume="23", issue="7", pages="1150-1160",
        doi="",
        is_chinese=True,
        abstract="综述青少年心理健康的影响因素及促进策略，涉及家庭、学校和社区多层次干预。",
        keywords=["青少年", "心理健康", "干预研究"],
        source="preset",
        relevance_note="青少年心理健康研究的框架参考",
    ),
    "陈会昌2012": LiteratureEntry(
        key="陈会昌2012",
        authors=["陈会昌"],
        year=2012,
        title="儿童社会性发展",
        journal="北京师范大学出版社",
        volume="", issue="", pages="",
        doi="",
        is_chinese=True,
        abstract="系统阐述儿童社会性发展的理论与实证研究，涵盖依恋、同伴关系、道德发展等主题。",
        keywords=["社会性发展", "儿童", "依恋", "同伴关系"],
        source="preset",
        relevance_note="儿童发展研究的理论基础",
    ),
    "雷雳2015": LiteratureEntry(
        key="雷雳2015",
        authors=["雷雳"],
        year=2015,
        title="青少年网络成瘾：理论、评估与干预",
        journal="心理科学进展",
        volume="23", issue="8", pages="1357-1368",
        doi="",
        is_chinese=True,
        abstract="从成因机制、评估方法和干预策略三方面系统综述青少年网络成瘾研究。",
        keywords=["网络成瘾", "青少年", "评估", "干预"],
        source="preset",
        relevance_note="网络成瘾评估量表的参考",
    ),
    # ---- 组织行为学 ----
    "张勉2006": LiteratureEntry(
        key="张勉2006",
        authors=["张勉", "张德"],
        year=2006,
        title="组织文化测量研究述评",
        journal="外国经济与管理",
        volume="28", issue="3", pages="33-40",
        doi="",
        is_chinese=True,
        abstract="系统评述国内外组织文化测量的主要量表和理论模型。",
        keywords=["组织文化", "测量", "量表"],
        source="preset",
        relevance_note="组织文化量表编制的参考",
    ),
    "李超平2008": LiteratureEntry(
        key="李超平2008",
        authors=["李超平", "时勘"],
        year=2008,
        title="变革型领导的结构与测量",
        journal="心理学报",
        volume="40", issue="4", pages="492-500",
        doi="",
        is_chinese=True,
        abstract="在中国组织情境下开发并验证变革型领导的多维测量工具。",
        keywords=["变革型领导", "量表编制", "中国情境"],
        source="preset",
        relevance_note="领导力量表中国化的范例",
    ),
    "王雁飞2015": LiteratureEntry(
        key="王雁飞2015",
        authors=["王雁飞", "朱瑜"],
        year=2015,
        title="心理资本理论与实证研究进展",
        journal="心理科学进展",
        volume="23", issue="6", pages="1035-1045",
        doi="",
        is_chinese=True,
        abstract="系统综述心理资本的概念界定、维度结构、测量工具及其在工作场所中的效应。",
        keywords=["心理资本", "积极组织行为学", "测量"],
        source="preset",
        relevance_note="心理资本量表设计的理论基础",
    ),
    "仲理峰2013": LiteratureEntry(
        key="仲理峰2013",
        authors=["仲理峰", "王小明", "Sandy J. Wayne", "Robert C. Liden"],
        year=2013,
        title="领导—成员交换理论研究的新进展",
        journal="心理科学进展",
        volume="21", issue="6", pages="1031-1041",
        doi="",
        is_chinese=True,
        abstract="回顾LMX理论的发展脉络，整合最新研究发现并提出未来研究方向。",
        keywords=["领导-成员交换", "LMX", "社会交换"],
        source="preset",
        relevance_note="组织行为研究中关系变量的理论基础",
    ),
    # ---- 教育心理学 ----
    "陈琦2011": LiteratureEntry(
        key="陈琦2011",
        authors=["陈琦", "刘儒德"],
        year=2011,
        title="当代教育心理学（第2版）",
        journal="北京师范大学出版社",
        volume="", issue="", pages="",
        doi="",
        is_chinese=True,
        abstract="全面介绍教育心理学的核心理论及其在教学实践中的应用。",
        keywords=["教育心理学", "学习理论", "教学实践"],
        source="preset",
        relevance_note="教育心理研究的理论基础",
    ),
    "庞维国2010": LiteratureEntry(
        key="庞维国2010",
        authors=["庞维国"],
        year=2010,
        title="自主学习：学与教的原理与策略",
        journal="华东师范大学出版社",
        volume="", issue="", pages="",
        doi="",
        is_chinese=True,
        abstract="系统阐述自主学习的理论模型、评估方法和教学促进策略。",
        keywords=["自主学习", "学习策略", "自我调节"],
        source="preset",
        relevance_note="学习动机与策略研究的理论框架",
    ),
    "周宗奎2014": LiteratureEntry(
        key="周宗奎2014",
        authors=["周宗奎", "孙晓军", "赵冬梅", "田媛", "范翠英"],
        year=2014,
        title="同伴关系的发展研究",
        journal="心理发展与教育",
        volume="30", issue="1", pages="1-10",
        doi="",
        is_chinese=True,
        abstract="系统回顾同伴关系的发展特点、测量方法和影响因素研究。",
        keywords=["同伴关系", "发展", "社交测量"],
        source="preset",
        relevance_note="同伴关系量表编制的参考",
    ),
    # ---- 人格心理学 ----
    "王登峰2005": LiteratureEntry(
        key="王登峰2005",
        authors=["王登峰", "崔红"],
        year=2005,
        title="中国人人格量表（QZPS）的编制过程与初步结果",
        journal="心理学报",
        volume="37", issue="5", pages="628-636",
        doi="",
        is_chinese=True,
        abstract="基于中国人人格结构理论，编制中国人人格量表并验证其信效度。",
        keywords=["人格量表", "中国人人格", "量表编制", "QZPS"],
        source="preset",
        relevance_note="本土化人格量表编制的范例",
    ),
    "张建新2006": LiteratureEntry(
        key="张建新2006",
        authors=["张建新", "周明洁"],
        year=2006,
        title="中国人人格结构探索：人格特质六因素模型",
        journal="心理科学进展",
        volume="14", issue="4", pages="574-585",
        doi="",
        is_chinese=True,
        abstract="探索中国人人格的六因素结构模型，比较与西方大五模型的异同。",
        keywords=["人格结构", "中国人人格", "六因素模型"],
        source="preset",
        relevance_note="本土化人格理论参考",
    ),
    # ---- 心理测量学 ----
    "漆书青2011": LiteratureEntry(
        key="漆书青2011",
        authors=["漆书青", "戴海琦", "丁树良"],
        year=2011,
        title="现代教育与心理测量学原理",
        journal="高等教育出版社",
        volume="", issue="", pages="",
        doi="",
        is_chinese=True,
        abstract="系统介绍经典测量理论、概化理论和项目反应理论三大测量理论体系。",
        keywords=["心理测量学", "CTT", "GT", "IRT"],
        source="preset",
        relevance_note="心理测量学理论的标准教材",
    ),
    "罗照盛2012": LiteratureEntry(
        key="罗照盛2012",
        authors=["罗照盛"],
        year=2012,
        title="项目反应理论基础",
        journal="北京师范大学出版社",
        volume="", issue="", pages="",
        doi="",
        is_chinese=True,
        abstract="系统介绍项目反应理论的基本模型、参数估计方法和在测验编制中的应用。",
        keywords=["项目反应理论", "IRT", "测验编制"],
        source="preset",
        relevance_note="IRT在量表优化中的应用",
    ),
    "温忠麟2012a": LiteratureEntry(
        key="温忠麟2012a",
        authors=["温忠麟", "叶宝娟"],
        year=2012,
        title="测验信度估计：从α系数到内部一致性信度",
        journal="心理学报",
        volume="44", issue="1", pages="121-130",
        doi="",
        is_chinese=True,
        abstract="系统比较不同信度估计方法的优劣，讨论α系数的使用条件和替代方案。",
        keywords=["信度估计", "Cronbach's α", "内部一致性"],
        source="preset",
        relevance_note="量表信度分析的权威参考",
    ),
    "侯杰泰2004": LiteratureEntry(
        key="侯杰泰2004",
        authors=["侯杰泰", "温忠麟", "成子娟"],
        year=2004,
        title="结构方程模型及其应用",
        journal="教育科学出版社",
        volume="", issue="", pages="",
        doi="",
        is_chinese=True,
        abstract="系统介绍结构方程模型的基本原理、分析步骤和在社会科学研究中的应用。",
        keywords=["结构方程模型", "SEM", "验证性因子分析"],
        source="preset",
        relevance_note="SEM/CFA分析的标准教科书",
    ),
    # ---- 实验设计 ----
    "舒华2015": LiteratureEntry(
        key="舒华2015",
        authors=["舒华", "张亚旭"],
        year=2015,
        title="心理学研究方法：实验设计和数据分析",
        journal="人民教育出版社",
        volume="", issue="", pages="",
        doi="",
        is_chinese=True,
        abstract="系统介绍心理学实验设计的原则、方法和相应的数据分析技术。",
        keywords=["实验设计", "数据分析", "研究方法"],
        source="preset",
        relevance_note="实验设计与数据分析的综合教材",
    ),
    "郭秀艳2017": LiteratureEntry(
        key="郭秀艳2017",
        authors=["郭秀艳"],
        year=2017,
        title="实验心理学（第2版）",
        journal="人民教育出版社",
        volume="", issue="", pages="",
        doi="",
        is_chinese=True,
        abstract="全面介绍实验心理学的经典范式和现代技术，包括行为实验和认知神经科学技术。",
        keywords=["实验心理学", "实验范式", "认知实验"],
        source="preset",
        relevance_note="实验范式设计的标准参考书",
    ),
    "张学民2014": LiteratureEntry(
        key="张学民2014",
        authors=["张学民"],
        year=2014,
        title="实验心理学纲要",
        journal="北京师范大学出版社",
        volume="", issue="", pages="",
        doi="",
        is_chinese=True,
        abstract="简明介绍实验心理学核心概念和常用实验范式。",
        keywords=["实验心理学", "实验范式", "实验设计"],
        source="preset",
        relevance_note="实验设计简明指南",
    ),
    # ---- 积极心理学 ----
    "任俊2012": LiteratureEntry(
        key="任俊2012",
        authors=["任俊"],
        year=2012,
        title="积极心理学",
        journal="上海教育出版社",
        volume="", issue="", pages="",
        doi="",
        is_chinese=True,
        abstract="系统介绍积极心理学的理论体系、研究方法和干预策略。",
        keywords=["积极心理学", "幸福感", "心理优势"],
        source="preset",
        relevance_note="积极心理学研究的理论基础",
    ),
    "苗元江2010": LiteratureEntry(
        key="苗元江2010",
        authors=["苗元江"],
        year=2010,
        title="心理学视野中的幸福：幸福感理论与测评研究",
        journal="中国社会科学出版社",
        volume="", issue="", pages="",
        doi="",
        is_chinese=True,
        abstract="从心理学角度系统考察幸福感的概念演变、理论模型和测量工具。",
        keywords=["幸福感", "主观幸福感", "心理幸福感"],
        source="preset",
        relevance_note="幸福感量表编制的理论参考",
    ),
    "郑雪2010": LiteratureEntry(
        key="郑雪2010",
        authors=["郑雪", "严标宾", "邱林"],
        year=2010,
        title="幸福心理学",
        journal="暨南大学出版社",
        volume="", issue="", pages="",
        doi="",
        is_chinese=True,
        abstract="全面介绍幸福感研究的理论基础、测量工具和跨文化发现。",
        keywords=["幸福感", "主观幸福感", "跨文化"],
        source="preset",
        relevance_note="幸福感研究的综合参考",
    ),
    # ---- 更多量表编制与验证 ----
    "汪向东1999": LiteratureEntry(
        key="汪向东1999",
        authors=["汪向东", "王希林", "马弘"],
        year=1999,
        title="心理卫生评定量表手册（增订版）",
        journal="中国心理卫生杂志社",
        volume="", issue="", pages="",
        doi="",
        is_chinese=True,
        abstract="汇集国内外常用心理卫生评定量表及其中国人群常模数据。",
        keywords=["心理卫生", "评定量表", "常模"],
        source="preset",
        relevance_note="中文量表编制的基准参考",
    ),
    "戴晓阳2010": LiteratureEntry(
        key="戴晓阳2010",
        authors=["戴晓阳"],
        year=2010,
        title="常用心理评估量表手册",
        journal="人民军医出版社",
        volume="", issue="", pages="",
        doi="",
        is_chinese=True,
        abstract="收集整理国内外常用的心理评估量表，提供量表文本和评分方法。",
        keywords=["心理评估", "量表手册", "临床评估"],
        source="preset",
        relevance_note="量表编制中常模参照的参考",
    ),
    "李虹2012": LiteratureEntry(
        key="李虹2012",
        authors=["李虹"],
        year=2012,
        title="健康心理学：健康促进与疾病预防",
        journal="北京大学出版社",
        volume="", issue="", pages="",
        doi="",
        is_chinese=True,
        abstract="从健康心理学视角系统介绍健康行为促进和疾病预防的理论与应用。",
        keywords=["健康心理学", "健康行为", "疾病预防"],
        source="preset",
        relevance_note="健康心理学量表的理论基础",
    ),
    "王才康2001": LiteratureEntry(
        key="王才康2001",
        authors=["王才康", "胡中锋", "刘勇"],
        year=2001,
        title="一般自我效能感量表的信度和效度研究",
        journal="应用心理学",
        volume="7", issue="1", pages="37-40",
        doi="",
        is_chinese=True,
        abstract="对Schwarzer一般自我效能感量表中文版进行信效度检验。",
        keywords=["自我效能感", "信度", "效度", "GSES"],
        source="preset",
        relevance_note="自我效能感量表中国化的经典研究",
    ),
    "杨中芳2007": LiteratureEntry(
        key="杨中芳2007",
        authors=["杨中芳", "彭泗清"],
        year=2007,
        title="中国人人际信任的概念化：一个人际关系的观点",
        journal="社会学研究",
        volume="", issue="2", pages="1-21",
        doi="",
        is_chinese=True,
        abstract="从人际关系视角重新概念化中国人的人际信任，提出本土化的信任理论。",
        keywords=["人际信任", "本土化", "中国人心理"],
        source="preset",
        relevance_note="本土化构念的理论建构范例",
    ),
    "张志学2010": LiteratureEntry(
        key="张志学2010",
        authors=["张志学"],
        year=2010,
        title="组织心理学研究的情境化及多层次理论",
        journal="心理学报",
        volume="42", issue="1", pages="10-21",
        doi="",
        is_chinese=True,
        abstract="讨论组织心理学研究中情境因素的重要性以及多层次理论建构方法。",
        keywords=["组织心理学", "情境化", "多层次理论"],
        source="preset",
        relevance_note="跨层次研究设计的理论指导",
    ),
    "甘怡群2014": LiteratureEntry(
        key="甘怡群2014",
        authors=["甘怡群"],
        year=2014,
        title="中介效应分析：原理、程序及Bootstrap方法的应用",
        journal="心理技术与应用",
        volume="", issue="3", pages="16-24",
        doi="",
        is_chinese=True,
        abstract="详细介绍中介效应分析的原理和Bootstrap方法的操作步骤。",
        keywords=["中介效应", "Bootstrap", "数据分析"],
        source="preset",
        relevance_note="Bootstrap中介效应实操指南",
    ),
    "叶宝娟2014": LiteratureEntry(
        key="叶宝娟2014",
        authors=["叶宝娟", "温忠麟"],
        year=2014,
        title="有调节的中介模型检验方法：竞争还是替代？",
        journal="心理学报",
        volume="46", issue="5", pages="714-726",
        doi="",
        is_chinese=True,
        abstract="系统比较有调节的中介模型和有中介的调节模型的检验方法。",
        keywords=["有调节的中介", "有中介的调节", "方法比较"],
        source="preset",
        relevance_note="复杂中介模型的检验方法",
    ),
    "罗胜强2014": LiteratureEntry(
        key="罗胜强2014",
        authors=["罗胜强", "姜嫄"],
        year=2014,
        title="管理学问卷调查研究方法",
        journal="重庆大学出版社",
        volume="", issue="", pages="",
        doi="",
        is_chinese=True,
        abstract="系统介绍管理学问卷调查研究的设计、实施和数据分析全过程。",
        keywords=["问卷调查研究", "管理学", "研究方法"],
        source="preset",
        relevance_note="问卷调查研究方法的综合指南",
    ),
    "邱皓政2013": LiteratureEntry(
        key="邱皓政2013",
        authors=["邱皓政"],
        year=2013,
        title="量化研究与统计分析：SPSS(PASW)数据分析范例解析",
        journal="重庆大学出版社",
        volume="", issue="", pages="",
        doi="",
        is_chinese=True,
        abstract="以SPSS为工具，系统讲解量化研究和统计分析的各种方法及其应用。",
        keywords=["量化研究", "SPSS", "统计方法"],
        source="preset",
        relevance_note="统计分析的实用参考书",
    ),
    "刘霞2013": LiteratureEntry(
        key="刘霞2013",
        authors=["刘霞", "赵景欣", "师保国"],
        year=2013,
        title="流动儿童的城市适应：理论与实证",
        journal="心理科学进展",
        volume="21", issue="9", pages="1579-1590",
        doi="",
        is_chinese=True,
        abstract="从生态系统理论视角综述流动儿童城市适应的影响因素和促进策略。",
        keywords=["流动儿童", "城市适应", "生态系统理论"],
        source="preset",
        relevance_note="特殊群体适应研究的理论框架",
    ),
    "任志洪2016": LiteratureEntry(
        key="任志洪2016",
        authors=["任志洪", "江光荣"],
        year=2016,
        title="网络化认知行为治疗的疗效及机制",
        journal="心理科学进展",
        volume="24", issue="10", pages="1587-1597",
        doi="",
        is_chinese=True,
        abstract="系统综述网络化CBT的疗效证据及起效机制。",
        keywords=["网络化CBT", "认知行为治疗", "疗效机制"],
        source="preset",
        relevance_note="数字化干预的设计参考",
    ),
    "周帆2014": LiteratureEntry(
        key="周帆2014",
        authors=["周帆", "王登峰"],
        year=2014,
        title="人格与工作绩效：中国人人格量表的预测效度",
        journal="心理学报",
        volume="46", issue="4", pages="531-539",
        doi="",
        is_chinese=True,
        abstract="使用中国人人格量表检验人格特质对工作绩效的预测作用。",
        keywords=["人格", "工作绩效", "QZPS", "预测效度"],
        source="preset",
        relevance_note="人格量表的效标关联效度研究范例",
    ),
}

# ============================================================
# 新增英文文献（40条）
# ============================================================

EXPANSION_ENGLISH = {
    # ---- 统计方法 ----
    "Hayes2017": LiteratureEntry(
        key="Hayes2017",
        authors=["Hayes, A. F."],
        year=2017,
        title="Introduction to mediation, moderation, and conditional process analysis: A regression-based approach (2nd ed.)",
        journal="Guilford Press",
        volume="", issue="", pages="",
        doi="",
        is_chinese=False,
        abstract="The authoritative text on mediation, moderation, and conditional process analysis using the PROCESS macro.",
        keywords=["mediation", "moderation", "PROCESS", "conditional process analysis"],
        source="preset",
        relevance_note="中介/调节分析的权威方法学参考",
    ),
    "Muthen2017": LiteratureEntry(
        key="Muthen2017",
        authors=["Muthén, L. K.", "Muthén, B. O."],
        year=2017,
        title="Mplus user's guide (8th ed.)",
        journal="Muthén & Muthén",
        volume="", issue="", pages="",
        doi="",
        is_chinese=False,
        abstract="The complete user guide for Mplus statistical software for latent variable modeling.",
        keywords=["Mplus", "SEM", "latent variable", "CFA"],
        source="preset",
        relevance_note="潜变量建模软件的操作手册",
    ),
    "Gelman2013": LiteratureEntry(
        key="Gelman2013",
        authors=["Gelman, A.", "Carlin, J. B.", "Stern, H. S.", "Dunson, D. B.", "Vehtari, A.", "Rubin, D. B."],
        year=2013,
        title="Bayesian data analysis (3rd ed.)",
        journal="CRC Press",
        volume="", issue="", pages="",
        doi="",
        is_chinese=False,
        abstract="Comprehensive treatment of Bayesian statistical methods with applications in social and behavioral sciences.",
        keywords=["Bayesian", "data analysis", "hierarchical models"],
        source="preset",
        relevance_note="贝叶斯统计的标准教科书",
    ),
    "McElreath2020": LiteratureEntry(
        key="McElreath2020",
        authors=["McElreath, R."],
        year=2020,
        title="Statistical rethinking: A Bayesian course with examples in R and Stan (2nd ed.)",
        journal="CRC Press",
        volume="", issue="", pages="",
        doi="",
        is_chinese=False,
        abstract="A practical introduction to Bayesian data analysis using R and Stan, with emphasis on multilevel models.",
        keywords=["Bayesian", "multilevel", "R", "Stan"],
        source="preset",
        relevance_note="多层模型的贝叶斯方法",
    ),
    "Kline2016": LiteratureEntry(
        key="Kline2016",
        authors=["Kline, R. B."],
        year=2016,
        title="Principles and practice of structural equation modeling (4th ed.)",
        journal="Guilford Press",
        volume="", issue="", pages="",
        doi="",
        is_chinese=False,
        abstract="Comprehensive guide to SEM covering path analysis, CFA, and latent variable models.",
        keywords=["SEM", "CFA", "path analysis", "latent variables"],
        source="preset",
        relevance_note="SEM理论与实践的权威教材",
    ),
    "Brown2015": LiteratureEntry(
        key="Brown2015",
        authors=["Brown, T. A."],
        year=2015,
        title="Confirmatory factor analysis for applied research (2nd ed.)",
        journal="Guilford Press",
        volume="", issue="", pages="",
        doi="",
        is_chinese=False,
        abstract="Practical guide to CFA with emphasis on applied research contexts, model fit evaluation, and modification.",
        keywords=["CFA", "factor analysis", "model fit", "measurement"],
        source="preset",
        relevance_note="CFA应用研究的标准参考书",
    ),
    "Westfall2014": LiteratureEntry(
        key="Westfall2014",
        authors=["Westfall, J.", "Kenny, D. A.", "Judd, C. M."],
        year=2014,
        title="Statistical power and optimal design in experiments in which samples of participants respond to samples of stimuli",
        journal="Journal of Experimental Psychology: General",
        volume="143", issue="5", pages="2020-2045",
        doi="10.1037/xge0000014",
        is_chinese=False,
        abstract="Presents a general framework for power analysis in experiments with crossed random effects of participants and stimuli.",
        keywords=["statistical power", "experimental design", "mixed models"],
        source="preset",
        relevance_note="混合效应设计的统计检验力分析",
    ),
    "Simmons2011": LiteratureEntry(
        key="Simmons2011",
        authors=["Simmons, J. P.", "Nelson, L. D.", "Simonsohn, U."],
        year=2011,
        title="False-positive psychology: Undisclosed flexibility in data collection and analysis allows presenting anything as significant",
        journal="Psychological Science",
        volume="22", issue="11", pages="1359-1366",
        doi="10.1177/0956797611417632",
        is_chinese=False,
        abstract="Demonstrates how researcher degrees of freedom can inflate false-positive rates and proposes disclosure requirements.",
        keywords=["false positives", "researcher degrees of freedom", "methodology"],
        source="preset",
        relevance_note="预注册和透明度的重要方法学依据",
    ),
    "Lakens2013": LiteratureEntry(
        key="Lakens2013",
        authors=["Lakens, D."],
        year=2013,
        title="Calculating and reporting effect sizes to facilitate cumulative science: A practical primer for t-tests and ANOVAs",
        journal="Frontiers in Psychology",
        volume="4", issue="", pages="863",
        doi="10.3389/fpsyg.2013.00863",
        is_chinese=False,
        abstract="Practical guide for calculating and interpreting effect sizes for common experimental designs.",
        keywords=["effect size", "Cohen's d", "eta-squared", "reporting"],
        source="preset",
        relevance_note="效应量计算与报告的实用指南",
    ),
    "Cumming2014": LiteratureEntry(
        key="Cumming2014",
        authors=["Cumming, G."],
        year=2014,
        title="The new statistics: Why and how",
        journal="Psychological Science",
        volume="25", issue="1", pages="7-29",
        doi="10.1177/0956797613504966",
        is_chinese=False,
        abstract="Argues for estimation-based approaches (effect sizes with CIs) over null hypothesis significance testing.",
        keywords=["new statistics", "estimation", "confidence intervals", "meta-analysis"],
        source="preset",
        relevance_note="新统计运动的核心理念与方法",
    ),
    # ---- 量表编制与心理测量 ----
    "DeVellis2017": LiteratureEntry(
        key="DeVellis2017",
        authors=["DeVellis, R. F."],
        year=2017,
        title="Scale development: Theory and applications (4th ed.)",
        journal="SAGE Publications",
        volume="", issue="", pages="",
        doi="",
        is_chinese=False,
        abstract="The definitive guide to scale development covering item writing, reliability, validity, and factor analysis.",
        keywords=["scale development", "psychometrics", "validity", "reliability"],
        source="preset",
        relevance_note="量表编制的权威指南",
    ),
    "Furr2014": LiteratureEntry(
        key="Furr2014",
        authors=["Furr, R. M.", "Bacharach, V. R."],
        year=2014,
        title="Psychometrics: An introduction (2nd ed.)",
        journal="SAGE Publications",
        volume="", issue="", pages="",
        doi="",
        is_chinese=False,
        abstract="Comprehensive introduction to psychometric theory and methods for scale construction and evaluation.",
        keywords=["psychometrics", "reliability", "validity", "factor analysis"],
        source="preset",
        relevance_note="心理测量学的入门教材",
    ),
    "Reise2014": LiteratureEntry(
        key="Reise2014",
        authors=["Reise, S. P.", "Waller, N. G."],
        year=2014,
        title="Item response theory and clinical measurement",
        journal="Annual Review of Clinical Psychology",
        volume="10", issue="", pages="127-152",
        doi="10.1146/annurev-clinpsy-032813-153658",
        is_chinese=False,
        abstract="Reviews IRT applications in clinical assessment, including DIF analysis and computerized adaptive testing.",
        keywords=["IRT", "clinical measurement", "DIF", "adaptive testing"],
        source="preset",
        relevance_note="IRT在临床量表中的应用",
    ),
    "Flake2020": LiteratureEntry(
        key="Flake2020",
        authors=["Flake, J. K.", "Fried, E. I."],
        year=2020,
        title="Measurement schmeasurement: Questionable measurement practices and how to avoid them",
        journal="Advances in Methods and Practices in Psychological Science",
        volume="3", issue="4", pages="456-465",
        doi="10.1177/2515245920952393",
        is_chinese=False,
        abstract="Identifies common questionable measurement practices and provides recommendations for improved measurement transparency.",
        keywords=["measurement", "questionable practices", "validity", "transparency"],
        source="preset",
        relevance_note="测量透明度与最佳实践",
    ),
    # ---- 问卷设计 ----
    "Dillman2014": LiteratureEntry(
        key="Dillman2014",
        authors=["Dillman, D. A.", "Smyth, J. D.", "Christian, L. M."],
        year=2014,
        title="Internet, phone, mail, and mixed-mode surveys: The tailored design method (4th ed.)",
        journal="John Wiley & Sons",
        volume="", issue="", pages="",
        doi="",
        is_chinese=False,
        abstract="Comprehensive guide to survey design across multiple modes of administration.",
        keywords=["survey design", "mixed-mode", "response rates", "questionnaire"],
        source="preset",
        relevance_note="问卷设计的综合方法论",
    ),
    "Tourangeau2000": LiteratureEntry(
        key="Tourangeau2000",
        authors=["Tourangeau, R.", "Rips, L. J.", "Rasinski, K."],
        year=2000,
        title="The psychology of survey response",
        journal="Cambridge University Press",
        volume="", issue="", pages="",
        doi="",
        is_chinese=False,
        abstract="Cognitive model of survey response process covering comprehension, retrieval, judgment, and response formatting.",
        keywords=["survey response", "cognitive processes", "questionnaire design"],
        source="preset",
        relevance_note="问卷作答认知过程的理论基础",
    ),
    "Krosnick2010": LiteratureEntry(
        key="Krosnick2010",
        authors=["Krosnick, J. A.", "Presser, S."],
        year=2010,
        title="Question and questionnaire design",
        journal="Handbook of Survey Research",
        volume="", issue="", pages="263-313",
        doi="",
        is_chinese=False,
        abstract="Comprehensive review of best practices in question wording, response options, and questionnaire structure.",
        keywords=["questionnaire design", "question wording", "response options"],
        source="preset",
        relevance_note="问卷题目撰写的最佳实践",
    ),
    # ---- 实验设计 ----
    "Kirk2013": LiteratureEntry(
        key="Kirk2013",
        authors=["Kirk, R. E."],
        year=2013,
        title="Experimental design: Procedures for the behavioral sciences (4th ed.)",
        journal="SAGE Publications",
        volume="", issue="", pages="",
        doi="",
        is_chinese=False,
        abstract="Classic comprehensive text on experimental design covering ANOVA, ANCOVA, and factorial designs.",
        keywords=["experimental design", "ANOVA", "factorial design", "ANCOVA"],
        source="preset",
        relevance_note="实验设计的经典教材",
    ),
    "Shadish2002": LiteratureEntry(
        key="Shadish2002",
        authors=["Shadish, W. R.", "Cook, T. D.", "Campbell, D. T."],
        year=2002,
        title="Experimental and quasi-experimental designs for generalized causal inference",
        journal="Houghton Mifflin",
        volume="", issue="", pages="",
        doi="",
        is_chinese=False,
        abstract="Definitive text on causal inference in experimental and quasi-experimental designs.",
        keywords=["causal inference", "quasi-experiment", "validity", "experimental design"],
        source="preset",
        relevance_note="因果推断与实验设计的权威著作",
    ),
    # ---- 元分析 ----
    "Borenstein2009": LiteratureEntry(
        key="Borenstein2009",
        authors=["Borenstein, M.", "Hedges, L. V.", "Higgins, J. P. T.", "Rothstein, H. R."],
        year=2009,
        title="Introduction to meta-analysis",
        journal="John Wiley & Sons",
        volume="", issue="", pages="",
        doi="",
        is_chinese=False,
        abstract="Comprehensive introduction to meta-analysis methods, including fixed and random effects models.",
        keywords=["meta-analysis", "effect size", "systematic review"],
        source="preset",
        relevance_note="元分析方法的权威教材",
    ),
    "Cumming2012": LiteratureEntry(
        key="Cumming2012",
        authors=["Cumming, G."],
        year=2012,
        title="Understanding the new statistics: Effect sizes, confidence intervals, and meta-analysis",
        journal="Routledge",
        volume="", issue="", pages="",
        doi="",
        is_chinese=False,
        abstract="Accessible introduction to estimation-based statistics emphasizing CIs and meta-analytic thinking.",
        keywords=["new statistics", "effect sizes", "confidence intervals", "meta-analysis"],
        source="preset",
        relevance_note="新统计方法的教学参考书",
    ),
    # ---- 开放科学 ----
    "Nosek2015": LiteratureEntry(
        key="Nosek2015",
        authors=["Nosek, B. A.", "Alter, G.", "Banks, G. C.", "Borsboom, D.", "Bowman, S. D.", "Breckler, S. J.", "...", "Yarkoni, T."],
        year=2015,
        title="Promoting an open research culture",
        journal="Science",
        volume="348", issue="6242", pages="1422-1425",
        doi="10.1126/science.aab2374",
        is_chinese=False,
        abstract="Outlines guidelines for transparency and openness promotion (TOP) in scientific publishing.",
        keywords=["open science", "transparency", "reproducibility", "TOP guidelines"],
        source="preset",
        relevance_note="开放科学实践的指导框架",
    ),
    "Munafo2017": LiteratureEntry(
        key="Munafo2017",
        authors=["Munafò, M. R.", "Nosek, B. A.", "Bishop, D. V. M.", "Button, K. S.", "Chambers, C. D.", "du Sert, N. P.", "...", "Ioannidis, J. P. A."],
        year=2017,
        title="A manifesto for reproducible science",
        journal="Nature Human Behaviour",
        volume="1", issue="", pages="0021",
        doi="10.1038/s41562-016-0021",
        is_chinese=False,
        abstract="Proposes measures to improve research reproducibility across the scientific enterprise.",
        keywords=["reproducibility", "open science", "research methods"],
        source="preset",
        relevance_note="可重复性科学的方法论基础",
    ),
    "Nelson2018": LiteratureEntry(
        key="Nelson2018",
        authors=["Nelson, L. D.", "Simmons, J.", "Simonsohn, U."],
        year=2018,
        title="Psychology's renaissance",
        journal="Annual Review of Psychology",
        volume="69", issue="", pages="511-534",
        doi="10.1146/annurev-psych-122216-011836",
        is_chinese=False,
        abstract="Reviews psychology's credibility revolution and the reforms in research practices.",
        keywords=["credibility revolution", "replication", "open science", "preregistration"],
        source="preset",
        relevance_note="心理学可信度革命的综述",
    ),
    # ---- 具体研究领域 ----
    "Baumeister2003": LiteratureEntry(
        key="Baumeister2003",
        authors=["Baumeister, R. F.", "Campbell, J. D.", "Krueger, J. I.", "Vohs, K. D."],
        year=2003,
        title="Does high self-esteem cause better performance, interpersonal success, happiness, or healthier lifestyles?",
        journal="Psychological Science in the Public Interest",
        volume="4", issue="1", pages="1-44",
        doi="10.1111/1529-1006.01431",
        is_chinese=False,
        abstract="Comprehensive review of the benefits and limitations of high self-esteem.",
        keywords=["self-esteem", "performance", "well-being", "review"],
        source="preset",
        relevance_note="自尊研究的经典综述",
    ),
    "Seligman2000": LiteratureEntry(
        key="Seligman2000",
        authors=["Seligman, M. E. P.", "Csikszentmihalyi, M."],
        year=2000,
        title="Positive psychology: An introduction",
        journal="American Psychologist",
        volume="55", issue="1", pages="5-14",
        doi="10.1037/0003-066X.55.1.5",
        is_chinese=False,
        abstract="Foundational article introducing the field of positive psychology and its research agenda.",
        keywords=["positive psychology", "well-being", "human strengths"],
        source="preset",
        relevance_note="积极心理学的奠基性文献",
    ),
    "Fredrickson2001": LiteratureEntry(
        key="Fredrickson2001",
        authors=["Fredrickson, B. L."],
        year=2001,
        title="The role of positive emotions in positive psychology: The broaden-and-build theory of positive emotions",
        journal="American Psychologist",
        volume="56", issue="3", pages="218-226",
        doi="10.1037/0003-066X.56.3.218",
        is_chinese=False,
        abstract="Proposes the broaden-and-build theory explaining how positive emotions expand cognitive and behavioral repertoires.",
        keywords=["positive emotions", "broaden-and-build", "resilience"],
        source="preset",
        relevance_note="积极情绪扩展建构理论",
    ),
    "Maslach2001": LiteratureEntry(
        key="Maslach2001",
        authors=["Maslach, C.", "Schaufeli, W. B.", "Leiter, M. P."],
        year=2001,
        title="Job burnout",
        journal="Annual Review of Psychology",
        volume="52", issue="", pages="397-422",
        doi="10.1146/annurev.psych.52.1.397",
        is_chinese=False,
        abstract="Comprehensive review of job burnout covering definition, measurement, antecedents, and consequences.",
        keywords=["burnout", "job stress", "MBI", "organizational"],
        source="preset",
        relevance_note="工作倦怠研究的权威综述",
    ),
    "Luthans2007": LiteratureEntry(
        key="Luthans2007",
        authors=["Luthans, F.", "Youssef, C. M.", "Avolio, B. J."],
        year=2007,
        title="Psychological capital: Developing the human competitive edge",
        journal="Oxford University Press",
        volume="", issue="", pages="",
        doi="",
        is_chinese=False,
        abstract="Introduces the concept of psychological capital (PsyCap) comprising self-efficacy, hope, optimism, and resilience.",
        keywords=["psychological capital", "PsyCap", "positive organizational behavior"],
        source="preset",
        relevance_note="心理资本理论与测量",
    ),
    "Gross2015": LiteratureEntry(
        key="Gross2015",
        authors=["Gross, J. J."],
        year=2015,
        title="Emotion regulation: Current status and future prospects",
        journal="Psychological Inquiry",
        volume="26", issue="1", pages="1-26",
        doi="10.1080/1047840X.2014.940781",
        is_chinese=False,
        abstract="Reviews the current state of emotion regulation research and outlines key future directions.",
        keywords=["emotion regulation", "reappraisal", "suppression", "ERQ"],
        source="preset",
        relevance_note="情绪调节研究的权威综述",
    ),
    "Hofmann2012": LiteratureEntry(
        key="Hofmann2012",
        authors=["Hofmann, S. G.", "Asnaani, A.", "Vonk, I. J. J.", "Sawyer, A. T.", "Fang, A."],
        year=2012,
        title="The efficacy of cognitive behavioral therapy: A review of meta-analyses",
        journal="Cognitive Therapy and Research",
        volume="36", issue="5", pages="427-440",
        doi="10.1007/s10608-012-9476-1",
        is_chinese=False,
        abstract="Reviews meta-analytic evidence for CBT efficacy across various psychological disorders.",
        keywords=["CBT", "meta-analysis", "efficacy", "treatment"],
        source="preset",
        relevance_note="CBT疗效的元分析综述",
    ),
    "Dweck2006": LiteratureEntry(
        key="Dweck2006",
        authors=["Dweck, C. S."],
        year=2006,
        title="Mindset: The new psychology of success",
        journal="Random House",
        volume="", issue="", pages="",
        doi="",
        is_chinese=False,
        abstract="Introduces the theory of fixed vs. growth mindsets and their implications for achievement and development.",
        keywords=["mindset", "implicit theories", "motivation", "achievement"],
        source="preset",
        relevance_note="内隐理论/心态研究的理论基础",
    ),
    "Duckworth2007": LiteratureEntry(
        key="Duckworth2007",
        authors=["Duckworth, A. L.", "Peterson, C.", "Matthews, M. D.", "Kelly, D. R."],
        year=2007,
        title="Grit: Perseverance and passion for long-term goals",
        journal="Journal of Personality and Social Psychology",
        volume="92", issue="6", pages="1087-1101",
        doi="10.1037/0022-3514.92.6.1087",
        is_chinese=False,
        abstract="Introduces the construct of grit and develops a validated self-report measure.",
        keywords=["grit", "perseverance", "achievement", "scale development"],
        source="preset",
        relevance_note="坚毅品格的构念与测量",
    ),
    "Diener1985": LiteratureEntry(
        key="Diener1985",
        authors=["Diener, E.", "Emmons, R. A.", "Larsen, R. J.", "Griffin, S."],
        year=1985,
        title="The Satisfaction With Life Scale",
        journal="Journal of Personality Assessment",
        volume="49", issue="1", pages="71-75",
        doi="10.1207/s15327752jpa4901_13",
        is_chinese=False,
        abstract="Develops and validates the Satisfaction With Life Scale (SWLS), a widely used measure of life satisfaction.",
        keywords=["life satisfaction", "SWLS", "well-being", "scale development"],
        source="preset",
        relevance_note="生活满意度量表的经典文献",
    ),
    "Watson1988": LiteratureEntry(
        key="Watson1988",
        authors=["Watson, D.", "Clark, L. A.", "Tellegen, A."],
        year=1988,
        title="Development and validation of brief measures of positive and negative affect: The PANAS scales",
        journal="Journal of Personality and Social Psychology",
        volume="54", issue="6", pages="1063-1070",
        doi="10.1037/0022-3514.54.6.1063",
        is_chinese=False,
        abstract="Develops the Positive and Negative Affect Schedule (PANAS) for measuring the two primary dimensions of mood.",
        keywords=["PANAS", "affect", "positive affect", "negative affect"],
        source="preset",
        relevance_note="正负性情绪量表的原创文献",
    ),
    "Cohen1983": LiteratureEntry(
        key="Cohen1983",
        authors=["Cohen, S.", "Kamarck, T.", "Mermelstein, R."],
        year=1983,
        title="A global measure of perceived stress",
        journal="Journal of Health and Social Behavior",
        volume="24", issue="4", pages="385-396",
        doi="10.2307/2136404",
        is_chinese=False,
        abstract="Develops the Perceived Stress Scale (PSS) to measure the degree to which situations are appraised as stressful.",
        keywords=["perceived stress", "PSS", "stress measurement"],
        source="preset",
        relevance_note="压力知觉量表的经典文献",
    ),
    "Zimet1988": LiteratureEntry(
        key="Zimet1988",
        authors=["Zimet, G. D.", "Dahlem, N. W.", "Zimet, S. G.", "Farley, G. K."],
        year=1988,
        title="The Multidimensional Scale of Perceived Social Support",
        journal="Journal of Personality Assessment",
        volume="52", issue="1", pages="30-41",
        doi="10.1207/s15327752jpa5201_2",
        is_chinese=False,
        abstract="Develops and validates a multidimensional measure of perceived social support from family, friends, and significant others.",
        keywords=["social support", "MSPSS", "scale development"],
        source="preset",
        relevance_note="社会支持量表的经典文献",
    ),
    "Schwarzer1995": LiteratureEntry(
        key="Schwarzer1995",
        authors=["Schwarzer, R.", "Jerusalem, M."],
        year=1995,
        title="Generalized Self-Efficacy Scale",
        journal="In J. Weinman, S. Wright, & M. Johnston (Eds.), Measures in health psychology: A user's portfolio (pp. 35-37). NFER-Nelson",
        volume="", issue="", pages="35-37",
        doi="",
        is_chinese=False,
        abstract="Presents the Generalized Self-Efficacy Scale (GSE), a widely used measure of perceived self-efficacy.",
        keywords=["self-efficacy", "GSE", "scale", "health psychology"],
        source="preset",
        relevance_note="一般自我效能感量表的源文献",
    ),
    "Preacher2008": LiteratureEntry(
        key="Preacher2008",
        authors=["Preacher, K. J.", "Hayes, A. F."],
        year=2008,
        title="Asymptotic and resampling strategies for assessing and comparing indirect effects in multiple mediator models",
        journal="Behavior Research Methods",
        volume="40", issue="3", pages="879-891",
        doi="10.3758/BRM.40.3.879",
        is_chinese=False,
        abstract="Introduces bootstrap methods for testing indirect effects in multiple mediator models.",
        keywords=["mediation", "bootstrap", "indirect effects", "multiple mediators"],
        source="preset",
        relevance_note="Bootstrap中介效应的经典方法论文献",
    ),
}


# ---- 补充条目（避免与已有预设键冲突）----
EXPANSION_CHINESE_EXTRA = {
    "彭凯平2016": LiteratureEntry(
        key="彭凯平2016",
        authors=["彭凯平", "喻丰"],
        year=2016,
        title="积极心理学与中国文化",
        journal="心理科学进展",
        volume="24", issue="9", pages="1403-1414",
        doi="",
        is_chinese=True,
        abstract="探讨积极心理学与中国传统文化的融合及其本土化应用。",
        keywords=["积极心理学", "中国文化", "本土化"],
        source="preset",
        relevance_note="积极心理学本土化的理论参考",
    ),
    "刘力2015": LiteratureEntry(
        key="刘力2015",
        authors=["刘力", "杨晓莉"],
        year=2015,
        title="民族认同与群体间态度研究",
        journal="心理科学进展",
        volume="23", issue="4", pages="642-652",
        doi="",
        is_chinese=True,
        abstract="系统综述民族认同的心理机制及其对群际态度的影响。",
        keywords=["民族认同", "群际态度", "社会认同"],
        source="preset",
        relevance_note="群际关系研究的理论框架",
    ),
    "隋洁2013": LiteratureEntry(
        key="隋洁2013",
        authors=["隋洁", "朱滢"],
        year=2013,
        title="自我参照效应的研究进展",
        journal="心理科学",
        volume="36", issue="3", pages="515-520",
        doi="",
        is_chinese=True,
        abstract="回顾自我参照效应的行为与神经机制研究。",
        keywords=["自我参照效应", "自我加工", "记忆"],
        source="preset",
        relevance_note="自我加工实验的范式参考",
    ),
    "沈模卫2012": LiteratureEntry(
        key="沈模卫2012",
        authors=["沈模卫", "高在峰", "张光强", "水仁德", "乔歆新"],
        year=2012,
        title="三维倾斜知觉中的视觉线索整合",
        journal="心理学报",
        volume="44", issue="6", pages="735-745",
        doi="",
        is_chinese=True,
        abstract="考察视觉系统中多线索整合的心理物理机制。",
        keywords=["视觉知觉", "线索整合", "心理物理学"],
        source="preset",
        relevance_note="感知觉实验的方法学参考",
    ),
    "莫雷2014": LiteratureEntry(
        key="莫雷2014",
        authors=["莫雷", "王瑞明", "冷英"],
        year=2014,
        title="文本阅读双加工理论与实验证据",
        journal="心理学报",
        volume="46", issue="6", pages="767-779",
        doi="",
        is_chinese=True,
        abstract="提出文本阅读的双加工理论并呈现系统的实验证据。",
        keywords=["文本阅读", "双加工", "阅读理解"],
        source="preset",
        relevance_note="语言认知研究的理论模型",
    ),
    "朱滢2007": LiteratureEntry(
        key="朱滢2007",
        authors=["朱滢"],
        year=2007,
        title="实验心理学（第2版）",
        journal="北京大学出版社",
        volume="", issue="", pages="",
        doi="",
        is_chinese=True,
        abstract="中国实验心理学经典教材，系统介绍实验设计、心理物理学和认知实验范式。",
        keywords=["实验心理学", "实验设计", "认知实验"],
        source="preset",
        relevance_note="实验心理学的标准教材",
    ),
    "林崇德2009": LiteratureEntry(
        key="林崇德2009",
        authors=["林崇德"],
        year=2009,
        title="发展心理学（第2版）",
        journal="人民教育出版社",
        volume="", issue="", pages="",
        doi="",
        is_chinese=True,
        abstract="系统阐述个体从出生到成年晚期的心理发展规律和理论。",
        keywords=["发展心理学", "毕生发展", "认知发展"],
        source="preset",
        relevance_note="发展心理学标准教材",
    ),
    "乐国安2012": LiteratureEntry(
        key="乐国安2012",
        authors=["乐国安"],
        year=2012,
        title="社会心理学（第3版）",
        journal="中国人民大学出版社",
        volume="", issue="", pages="",
        doi="",
        is_chinese=True,
        abstract="全面介绍社会心理学的核心理论和最新研究进展。",
        keywords=["社会心理学", "社会认知", "群体过程"],
        source="preset",
        relevance_note="社会心理学的标准教材",
    ),
    "车宏生2016": LiteratureEntry(
        key="车宏生2016",
        authors=["车宏生", "朱敏"],
        year=2016,
        title="心理统计与测量",
        journal="北京师范大学出版社",
        volume="", issue="", pages="",
        doi="",
        is_chinese=True,
        abstract="结合心理统计与测量的理论与实践，覆盖描述统计、推断统计和心理测量学基础。",
        keywords=["心理统计", "心理测量", "统计方法"],
        source="preset",
        relevance_note="心理统计与测量的整合教材",
    ),
    "金盛华2010": LiteratureEntry(
        key="金盛华2010",
        authors=["金盛华"],
        year=2010,
        title="社会心理学（第2版）",
        journal="高等教育出版社",
        volume="", issue="", pages="",
        doi="",
        is_chinese=True,
        abstract="系统阐述社会心理学的核心理论与研究，侧重中国社会情境。",
        keywords=["社会心理学", "中国社会", "人际交往"],
        source="preset",
        relevance_note="社会心理学本土化教材",
    ),
}

EXPANSION_ENGLISH_EXTRA = {
    "OpenScienceCollab2015": LiteratureEntry(
        key="OpenScienceCollab2015",
        authors=["Open Science Collaboration"],
        year=2015,
        title="Estimating the reproducibility of psychological science",
        journal="Science",
        volume="349", issue="6251", pages="aac4716",
        doi="10.1126/science.aac4716",
        is_chinese=False,
        abstract="Large-scale replication project estimating the reproducibility of 100 psychology studies.",
        keywords=["reproducibility", "replication", "open science"],
        source="preset",
        relevance_note="心理学可重复性项目的里程碑研究",
    ),
    "Button2013": LiteratureEntry(
        key="Button2013",
        authors=["Button, K. S.", "Ioannidis, J. P. A.", "Mokrysz, C.", "Nosek, B. A.", "Flint, J.", "Robinson, E. S. J.", "Munafò, M. R."],
        year=2013,
        title="Power failure: Why small sample size undermines the reliability of neuroscience",
        journal="Nature Reviews Neuroscience",
        volume="14", issue="5", pages="365-376",
        doi="10.1038/nrn3475",
        is_chinese=False,
        abstract="Demonstrates how low statistical power reduces the reliability of research findings in neuroscience and psychology.",
        keywords=["statistical power", "sample size", "reliability", "replication"],
        source="preset",
        relevance_note="统计检验力与样本量的重要论证",
    ),
    "Rosenthal1979": LiteratureEntry(
        key="Rosenthal1979",
        authors=["Rosenthal, R."],
        year=1979,
        title="The file drawer problem and tolerance for null results",
        journal="Psychological Bulletin",
        volume="86", issue="3", pages="638-641",
        doi="10.1037/0033-2909.86.3.638",
        is_chinese=False,
        abstract="Introduces the file drawer problem where non-significant results are less likely to be published.",
        keywords=["publication bias", "file drawer", "meta-analysis"],
        source="preset",
        relevance_note="发表偏倚的经典论述",
    ),
    "John2012": LiteratureEntry(
        key="John2012",
        authors=["John, O. P.", "Soto, C. J."],
        year=2012,
        title="The Big Five Inventory: Versions 4a and 54",
        journal="University of California, Berkeley",
        volume="", issue="", pages="",
        doi="",
        is_chinese=False,
        abstract="Documents the development and psychometric properties of the Big Five Inventory (BFI).",
        keywords=["Big Five", "personality", "BFI", "scale"],
        source="preset",
        relevance_note="大五人格量表的源文献",
    ),
    "Gosling2003": LiteratureEntry(
        key="Gosling2003",
        authors=["Gosling, S. D.", "Rentfrow, P. J.", "Swann, W. B."],
        year=2003,
        title="A very brief measure of the Big-Five personality domains",
        journal="Journal of Research in Personality",
        volume="37", issue="6", pages="504-528",
        doi="10.1016/S0092-6566(03)00046-1",
        is_chinese=False,
        abstract="Develops the Ten-Item Personality Inventory (TIPI), a brief measure of Big Five dimensions.",
        keywords=["Big Five", "TIPI", "brief measure", "personality"],
        source="preset",
        relevance_note="简版人格量表的开发范例",
    ),
    "Higgins2003": LiteratureEntry(
        key="Higgins2003",
        authors=["Higgins, J. P. T.", "Thompson, S. G.", "Deeks, J. J.", "Altman, D. G."],
        year=2003,
        title="Measuring inconsistency in meta-analyses",
        journal="BMJ",
        volume="327", issue="7414", pages="557-560",
        doi="10.1136/bmj.327.7414.557",
        is_chinese=False,
        abstract="Introduces the I² statistic for quantifying heterogeneity in meta-analysis.",
        keywords=["I-squared", "heterogeneity", "meta-analysis"],
        source="preset",
        relevance_note="元分析异质性检验的方法论文献",
    ),
    "Rosenberg1965": LiteratureEntry(
        key="Rosenberg1965",
        authors=["Rosenberg, M."],
        year=1965,
        title="Society and the adolescent self-image",
        journal="Princeton University Press",
        volume="", issue="", pages="",
        doi="",
        is_chinese=False,
        abstract="Introduces the Rosenberg Self-Esteem Scale (RSES), the most widely used measure of global self-esteem.",
        keywords=["self-esteem", "RSES", "scale development", "adolescent"],
        source="preset",
        relevance_note="自尊量表的经典源文献",
    ),
    "Beck1996": LiteratureEntry(
        key="Beck1996",
        authors=["Beck, A. T.", "Steer, R. A.", "Brown, G. K."],
        year=1996,
        title="Manual for the Beck Depression Inventory-II",
        journal="Psychological Corporation",
        volume="", issue="", pages="",
        doi="",
        is_chinese=False,
        abstract="Technical manual for the BDI-II, one of the most widely used depression screening instruments.",
        keywords=["BDI-II", "depression", "assessment", "clinical"],
        source="preset",
        relevance_note="抑郁量表的技术手册",
    ),
    "Spielberger1983": LiteratureEntry(
        key="Spielberger1983",
        authors=["Spielberger, C. D.", "Gorsuch, R. L.", "Lushene, R.", "Vagg, P. R.", "Jacobs, G. A."],
        year=1983,
        title="Manual for the State-Trait Anxiety Inventory",
        journal="Consulting Psychologists Press",
        volume="", issue="", pages="",
        doi="",
        is_chinese=False,
        abstract="Technical manual for the STAI, the most widely used measure of state and trait anxiety.",
        keywords=["STAI", "anxiety", "state-trait", "assessment"],
        source="preset",
        relevance_note="状态-特质焦虑量表的技术手册",
    ),
    "Wong2009": LiteratureEntry(
        key="Wong2009",
        authors=["Wong, P. T. P."],
        year=2009,
        title="Existential positive psychology",
        journal="In S. J. Lopez (Ed.), Encyclopedia of positive psychology (pp. 361-368). Wiley-Blackwell",
        volume="", issue="", pages="361-368",
        doi="",
        is_chinese=False,
        abstract="Introduces existential positive psychology integrating existential psychology with positive psychology.",
        keywords=["existential psychology", "positive psychology", "meaning"],
        source="preset",
        relevance_note="存在主义积极心理学的理论参考",
    ),
}


def get_expansion_entries():
    """返回所有扩展文献条目"""
    return {
        **EXPANSION_CHINESE,
        **EXPANSION_CHINESE_EXTRA,
        **EXPANSION_ENGLISH,
        **EXPANSION_ENGLISH_EXTRA,
    }
